[package]
name = "csv_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
indicatif = "0.17.9"
reqwest = { version = "0.12.9", features = ["stream"] }
futures-util = "0.3.31"
tokio = { version = "1.0", features = ["full"] }
